const products = [
  {
    id: 0,
    name: "Retniol serum +B5",
    price: 60,
    description: "A concantrated Hydration <br> support formuls",
    size: "60ml",
    instock: 100,
    image: "images/ord.jpg",
  },
  {
    id: 1,
    name: "Nicinmaide 10%",
    price: 70,
    description: "A concantrated Hydration <br> support formuls",
    size: "60ml",
    instock: 5,
    image: "images/po.jpg",
  },
  {
    id: 2,
    name: "Amino Acid+B5",
    price: 60,
    description: "A concantrated Hydration <br> support formuls",
    size: "60ml",
    instock: 10,
    image: "images/za.jpg",
  },
  {
    id: 3,
    name: "Lactic Acid",
    price: 60,
    description: "A concantrated Hydration <br> support formuls",
    size: "50ml",
    instock: 20,
    image: "images/brown.jpg",
  },
  {
    id: 4,
    name: "Haylyronic Acid",
    price: 60,
    description: "A concantrated Hydration <br> support formuls",
    size: "60ml",
    instock: 100,
    image: "images/rdn-glucoside-foaming-cleanser-150ml.jpg",
  },
];